<?php

namespace App;

use App\Scopes\BuyerScope;

class Buyer extends User
{
    //
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(New BuyerScope);
    }

    public function transactions(){
        return $this->hasMany(Transaction::class);
    }
}
