<?php

namespace App;

use App\Scopes\SellerScope;

class Seller extends User
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        parent::addGlobalScope(New SellerScope);
    }

    public function products(){
        return $this->hasMany(Product::class);
    }
}
